import type { ProviderId } from "@/lib/agent/model-gateway-types";

export type ModelCatalogSource =
  | "snapshot"
  | "models_dev"
  | "vercel_gateway"
  | "user"
  | "local";

export type CatalogReasoningEffort =
  | "none"
  | "minimal"
  | "low"
  | "medium"
  | "high"
  | "xhigh"
  | "max"
  | "default"
  | null;

export type ReasoningOption =
  | { type: "toggle" }
  | { type: "effort"; values: CatalogReasoningEffort[] }
  | { type: "budget_tokens"; min?: number; max?: number };

export interface ModelCatalogEntry {
  model_id: string;
  label: string;
  provider_id: ProviderId;
  api_model_id?: string;
  input_price_per_1m: number | null;
  output_price_per_1m: number | null;
  cached_price_per_1m: number | null;
  /** Cache-write price per million input tokens when separately billed. */
  cache_write_price_per_1m?: number | null;
  context_window: number | null;
  /** Source that supplied the context-window value. */
  context_window_source?: ModelCatalogSource | "fallback";
  /** Time the context-window metadata was fetched or snapshotted. */
  context_window_fetched_at?: string;
  /** True when Orion substituted its unknown-model fallback. */
  context_window_is_fallback?: boolean;
  max_output_tokens: number | null;
  supports_image_input?: boolean;
  supports_tool_calling?: boolean;
  supports_forced_tool_choice?: boolean;
  supports_reasoning?: boolean;
  /** Optional per-model reasoning controls reported by the live catalog. */
  reasoning_options?: ReasoningOption[];
  long_context_threshold: number | null;
  long_context_input_price_per_1m: number | null;
  long_context_output_price_per_1m: number | null;
  long_context_cached_price_per_1m?: number | null;
  long_context_cache_write_price_per_1m?: number | null;
  client_avail: boolean;
  pinned_by_default: boolean;
  created_at: string;
  source: ModelCatalogSource;
}

type RawModelCatalogEntry = Omit<ModelCatalogEntry, "source"> & {
  source?: ModelCatalogSource;
};

const CATALOG_CREATED_AT = "2026-05-17T00:00:00.000Z";

export const MODEL_CATALOG: RawModelCatalogEntry[] = [
  {
    model_id: "ollama-local",
    label: "Ollama",
    provider_id: "ollama",
    input_price_per_1m: 0,
    output_price_per_1m: 0,
    cached_price_per_1m: null,
    context_window: 32768,
    max_output_tokens: null,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "lmstudio-local",
    label: "LM Studio",
    provider_id: "lmstudio",
    input_price_per_1m: 0,
    output_price_per_1m: 0,
    cached_price_per_1m: null,
    context_window: 32768,
    max_output_tokens: null,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "mlx-local",
    label: "MLX",
    provider_id: "mlx",
    input_price_per_1m: 0,
    output_price_per_1m: 0,
    cached_price_per_1m: null,
    context_window: 32768,
    max_output_tokens: null,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "custom-local",
    label: "Custom Endpoint",
    provider_id: "custom",
    input_price_per_1m: 0,
    output_price_per_1m: 0,
    cached_price_per_1m: null,
    context_window: 32768,
    max_output_tokens: null,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "llama-3.3-70b-versatile",
    label: "Llama 3.3 70B",
    provider_id: "groq",
    input_price_per_1m: null,
    output_price_per_1m: null,
    cached_price_per_1m: null,
    context_window: 131072,
    max_output_tokens: null,
    supports_image_input: false,
    supports_tool_calling: true,
    supports_reasoning: false,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "qwen/qwen3-32b",
    label: "Qwen3 32B",
    provider_id: "groq",
    input_price_per_1m: null,
    output_price_per_1m: null,
    cached_price_per_1m: null,
    context_window: 131072,
    max_output_tokens: null,
    supports_image_input: false,
    supports_tool_calling: true,
    supports_reasoning: true,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "llama-4-scout-17b-16e-instruct",
    label: "Llama 4 Scout",
    provider_id: "cerebras",
    input_price_per_1m: null,
    output_price_per_1m: null,
    cached_price_per_1m: null,
    context_window: 131072,
    max_output_tokens: null,
    supports_image_input: false,
    supports_tool_calling: true,
    supports_reasoning: false,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "openai/gpt-oss-120b",
    label: "GPT-OSS 120B",
    provider_id: "vercel",
    input_price_per_1m: null,
    output_price_per_1m: null,
    cached_price_per_1m: null,
    context_window: 131072,
    max_output_tokens: null,
    supports_image_input: false,
    supports_tool_calling: true,
    supports_reasoning: true,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "moonshotai/kimi-k2.5",
    label: "Kimi K2.5",
    provider_id: "vercel",
    input_price_per_1m: null,
    output_price_per_1m: null,
    cached_price_per_1m: null,
    context_window: 131072,
    max_output_tokens: null,
    supports_image_input: false,
    supports_tool_calling: true,
    supports_reasoning: true,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.5",
    label: "GPT-5.5",
    provider_id: "openai",
    input_price_per_1m: 5,
    output_price_per_1m: 30,
    cached_price_per_1m: 0.5,
    context_window: 1050000,
    max_output_tokens: 128000,
    long_context_threshold: 272000,
    long_context_input_price_per_1m: 10,
    long_context_output_price_per_1m: 45,
    client_avail: true,
    pinned_by_default: true,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.6-terra",
    label: "GPT-5.6 Terra",
    provider_id: "openai",
    input_price_per_1m: 2.5,
    output_price_per_1m: 15,
    cached_price_per_1m: 0.25,
    context_window: 1050000,
    max_output_tokens: 128000,
    supports_tool_calling: true,
    supports_reasoning: true,
    long_context_threshold: 272000,
    long_context_input_price_per_1m: 5,
    long_context_output_price_per_1m: 22.5,
    client_avail: true,
    pinned_by_default: true,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.6-luna",
    label: "GPT-5.6 Luna",
    provider_id: "openai",
    input_price_per_1m: 1,
    output_price_per_1m: 6,
    cached_price_per_1m: 0.1,
    context_window: 1050000,
    max_output_tokens: 128000,
    supports_tool_calling: true,
    supports_reasoning: true,
    long_context_threshold: 272000,
    long_context_input_price_per_1m: 2,
    long_context_output_price_per_1m: 9,
    client_avail: true,
    pinned_by_default: true,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "claude-opus-4-7",
    label: "Claude Opus 4.7",
    provider_id: "anthropic",
    input_price_per_1m: 5,
    output_price_per_1m: 25,
    cached_price_per_1m: 0.5,
    context_window: 1000000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: true,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemini-3.1-pro-preview",
    label: "Gemini 3.1 Pro",
    provider_id: "google",
    input_price_per_1m: 2,
    output_price_per_1m: 12,
    cached_price_per_1m: 0.2,
    context_window: 1048576,
    max_output_tokens: 65536,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: true,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemini-3-flash-preview",
    label: "Gemini 3 Flash",
    provider_id: "google",
    input_price_per_1m: 0.5,
    output_price_per_1m: 3,
    cached_price_per_1m: 0.05,
    context_window: 1048576,
    max_output_tokens: 65536,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: true,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemini-3.5-flash",
    label: "Gemini 3.5 Flash",
    provider_id: "google",
    input_price_per_1m: 1.5,
    output_price_per_1m: 9,
    cached_price_per_1m: 0.15,
    context_window: 1048576,
    max_output_tokens: 65536,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemini-3.1-flash-lite",
    label: "Gemini 3.1 Flash-Lite",
    provider_id: "google",
    input_price_per_1m: 0.25,
    output_price_per_1m: 1.5,
    cached_price_per_1m: 0.025,
    context_window: 1048576,
    max_output_tokens: 65536,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemini-2.5-pro",
    label: "Gemini 2.5 Pro",
    provider_id: "google",
    input_price_per_1m: 1.25,
    output_price_per_1m: 10,
    cached_price_per_1m: 0.125,
    context_window: 1048576,
    max_output_tokens: 65536,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemini-2.5-flash",
    label: "Gemini 2.5 Flash",
    provider_id: "google",
    input_price_per_1m: 0.3,
    output_price_per_1m: 2.5,
    cached_price_per_1m: 0.03,
    context_window: 1048576,
    max_output_tokens: 65536,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemini-2.5-flash-lite",
    label: "Gemini 2.5 Flash-Lite",
    provider_id: "google",
    input_price_per_1m: 0.1,
    output_price_per_1m: 0.4,
    cached_price_per_1m: 0.01,
    context_window: 1048576,
    max_output_tokens: 65536,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemma-4-31b-it",
    label: "Gemma 4 31B",
    provider_id: "google",
    input_price_per_1m: 0,
    output_price_per_1m: 0,
    cached_price_per_1m: null,
    context_window: 262144,
    max_output_tokens: 8192,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gemma-4-26b-a4b-it",
    label: "Gemma 4 26B A4B",
    provider_id: "google",
    input_price_per_1m: 0,
    output_price_per_1m: 0,
    cached_price_per_1m: null,
    context_window: 262144,
    max_output_tokens: 8192,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "claude-sonnet-4-6",
    label: "Claude Sonnet 4.6",
    provider_id: "anthropic",
    input_price_per_1m: 3,
    output_price_per_1m: 15,
    cached_price_per_1m: 0.3,
    context_window: 1000000,
    max_output_tokens: 64000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: true,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "claude-opus-4-6",
    label: "Claude Opus 4.6",
    provider_id: "anthropic",
    input_price_per_1m: 5,
    output_price_per_1m: 25,
    cached_price_per_1m: 0.5,
    context_window: 1000000,
    max_output_tokens: 8192,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "claude-opus-4-5-20251101",
    label: "Claude Opus 4.5",
    provider_id: "anthropic",
    input_price_per_1m: 5,
    output_price_per_1m: 25,
    cached_price_per_1m: 0.5,
    context_window: 200000,
    max_output_tokens: 8192,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "claude-sonnet-4-5",
    label: "Claude Sonnet 4.5",
    provider_id: "anthropic",
    input_price_per_1m: 3,
    output_price_per_1m: 15,
    cached_price_per_1m: 0.3,
    context_window: 1000000,
    max_output_tokens: 64000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "claude-haiku-4-5",
    label: "Claude Haiku 4.5",
    provider_id: "anthropic",
    input_price_per_1m: 1,
    output_price_per_1m: 5,
    cached_price_per_1m: 0.1,
    context_window: 200000,
    max_output_tokens: 8192,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "claude-opus-4-1",
    label: "Claude Opus 4.1",
    provider_id: "anthropic",
    input_price_per_1m: 15,
    output_price_per_1m: 75,
    cached_price_per_1m: 1.5,
    context_window: 200000,
    max_output_tokens: 8192,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "claude-sonnet-4",
    label: "Claude Sonnet 4",
    provider_id: "anthropic",
    input_price_per_1m: 3,
    output_price_per_1m: 15,
    cached_price_per_1m: 0.3,
    context_window: 1000000,
    max_output_tokens: 64000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.4",
    label: "GPT-5.4",
    provider_id: "openai",
    input_price_per_1m: 2.5,
    output_price_per_1m: 15,
    cached_price_per_1m: 0.25,
    context_window: 1050000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.4-pro",
    label: "GPT-5.4 Pro",
    provider_id: "openai",
    input_price_per_1m: 30,
    output_price_per_1m: 180,
    cached_price_per_1m: null,
    context_window: 1050000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.4-mini",
    label: "GPT-5.4 Mini",
    provider_id: "openai",
    input_price_per_1m: 0.75,
    output_price_per_1m: 4.5,
    cached_price_per_1m: 0.075,
    context_window: 400000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.4-nano",
    label: "GPT-5.4 Nano",
    provider_id: "openai",
    input_price_per_1m: 0.2,
    output_price_per_1m: 1.25,
    cached_price_per_1m: 0.02,
    context_window: 400000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.3",
    label: "GPT-5.3",
    provider_id: "openai",
    input_price_per_1m: 1.75,
    output_price_per_1m: 14,
    cached_price_per_1m: 0.175,
    context_window: 400000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.3-codex",
    label: "GPT-5.3 Codex",
    provider_id: "openai",
    input_price_per_1m: 1.25,
    output_price_per_1m: 10,
    cached_price_per_1m: 0.125,
    context_window: 400000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.2",
    label: "GPT-5.2",
    provider_id: "openai",
    input_price_per_1m: 1.75,
    output_price_per_1m: 14,
    cached_price_per_1m: 0.175,
    context_window: 400000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5.2-pro",
    label: "GPT-5.2 Pro",
    provider_id: "openai",
    input_price_per_1m: 21,
    output_price_per_1m: 168,
    cached_price_per_1m: null,
    context_window: 400000,
    max_output_tokens: 128000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5-mini",
    label: "GPT-5 Mini",
    provider_id: "openai",
    input_price_per_1m: 0.25,
    output_price_per_1m: 2,
    cached_price_per_1m: 0.025,
    context_window: 128000,
    max_output_tokens: 65536,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "gpt-5-nano",
    label: "GPT-5 Nano",
    provider_id: "openai",
    input_price_per_1m: 0.05,
    output_price_per_1m: 0.4,
    cached_price_per_1m: 0.005,
    context_window: 128000,
    max_output_tokens: 32768,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "o3",
    label: "o3",
    provider_id: "openai",
    input_price_per_1m: 2,
    output_price_per_1m: 8,
    cached_price_per_1m: 0.5,
    context_window: 200000,
    max_output_tokens: 100000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "o3-pro",
    label: "o3 Pro",
    provider_id: "openai",
    input_price_per_1m: 20,
    output_price_per_1m: 80,
    cached_price_per_1m: null,
    context_window: 200000,
    max_output_tokens: 100000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "o3-mini",
    label: "o3 Mini",
    provider_id: "openai",
    input_price_per_1m: 1.1,
    output_price_per_1m: 4.4,
    cached_price_per_1m: 0.55,
    context_window: 200000,
    max_output_tokens: 100000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-4.20-0309-reasoning",
    label: "Grok 4.20 Reasoning",
    provider_id: "xai",
    input_price_per_1m: 2,
    output_price_per_1m: 6,
    cached_price_per_1m: 0.2,
    context_window: 2000000,
    max_output_tokens: 30000,
    long_context_threshold: 200000,
    long_context_input_price_per_1m: 4,
    long_context_output_price_per_1m: 12,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-4.20-0309-non-reasoning",
    label: "Grok 4.20 Non-Reasoning",
    provider_id: "xai",
    input_price_per_1m: 2,
    output_price_per_1m: 6,
    cached_price_per_1m: 0.2,
    context_window: 2000000,
    max_output_tokens: 30000,
    long_context_threshold: 200000,
    long_context_input_price_per_1m: 4,
    long_context_output_price_per_1m: 12,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-4.20-multi-agent-0309",
    label: "Grok 4.20 Multi-Agent",
    provider_id: "xai",
    input_price_per_1m: 2,
    output_price_per_1m: 6,
    cached_price_per_1m: 0.2,
    context_window: 2000000,
    max_output_tokens: 30000,
    long_context_threshold: 200000,
    long_context_input_price_per_1m: 4,
    long_context_output_price_per_1m: 12,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-4-1-fast-reasoning",
    label: "Grok 4.1 Fast Reasoning",
    provider_id: "xai",
    input_price_per_1m: 0.2,
    output_price_per_1m: 0.5,
    cached_price_per_1m: 0.05,
    context_window: 2000000,
    max_output_tokens: 30000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-4-1-fast-non-reasoning",
    label: "Grok 4.1 Fast Non-Reasoning",
    provider_id: "xai",
    input_price_per_1m: 0.2,
    output_price_per_1m: 0.5,
    cached_price_per_1m: 0.05,
    context_window: 2000000,
    max_output_tokens: 30000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-code-fast-1",
    label: "Grok Code Fast 1",
    provider_id: "xai",
    input_price_per_1m: 0.2,
    output_price_per_1m: 1.5,
    cached_price_per_1m: 0.02,
    context_window: 256000,
    max_output_tokens: 30000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-4-fast-reasoning",
    label: "Grok 4 Fast Reasoning",
    provider_id: "xai",
    input_price_per_1m: 0.2,
    output_price_per_1m: 0.5,
    cached_price_per_1m: 0.05,
    context_window: 2000000,
    max_output_tokens: 30000,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-4",
    label: "Grok 4",
    provider_id: "xai",
    input_price_per_1m: 3,
    output_price_per_1m: 15,
    cached_price_per_1m: null,
    context_window: 256000,
    max_output_tokens: 16384,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
  {
    model_id: "grok-3-mini",
    label: "Grok 3 Mini",
    provider_id: "xai",
    input_price_per_1m: 0.3,
    output_price_per_1m: 0.5,
    cached_price_per_1m: null,
    context_window: 131072,
    max_output_tokens: 8192,
    long_context_threshold: null,
    long_context_input_price_per_1m: null,
    long_context_output_price_per_1m: null,
    client_avail: true,
    pinned_by_default: false,
    created_at: CATALOG_CREATED_AT,
  },
];

/** Hosted catalog models are known multimodal unless explicitly overridden. */
function defaultSupportsImageInput(model: { provider_id: ProviderId }): boolean {
  if (
    model.provider_id === "ollama" ||
    model.provider_id === "lmstudio" ||
    model.provider_id === "mlx" ||
    model.provider_id === "custom"
  ) {
    return false;
  }
  return true;
}

/** Direct providers with known reliable specific-tool forcing support. */
function defaultSupportsForcedToolChoice(model: { provider_id: ProviderId }): boolean {
  return (
    model.provider_id === "openai" ||
    model.provider_id === "anthropic" ||
    model.provider_id === "google"
  );
}

export const CLIENT_MODEL_CATALOG = MODEL_CATALOG.filter(
  (model) => model.client_avail
).map((model) => ({
  ...model,
  source: model.source ?? "snapshot",
  supports_image_input: model.supports_image_input ?? defaultSupportsImageInput(model),
  supports_forced_tool_choice:
    model.supports_forced_tool_choice ?? defaultSupportsForcedToolChoice(model),
}));

export function getModelCatalogEntry(
  modelId: string
): ModelCatalogEntry | undefined {
  return CLIENT_MODEL_CATALOG.find((model) => model.model_id === modelId);
}

export function isKnownProvider(provider: string): provider is ProviderId {
  return (
    provider === "openai" ||
    provider === "anthropic" ||
    provider === "google" ||
    provider === "xai" ||
    provider === "groq" ||
    provider === "cerebras" ||
    provider === "vercel" ||
    provider === "ollama" ||
    provider === "lmstudio" ||
    provider === "mlx" ||
    provider === "custom" ||
    CLIENT_MODEL_CATALOG.some((model) => model.provider_id === provider)
  );
}

export interface ProviderCatalogMeta {
  id: ProviderId;
  label: string;
  credentialKind: "api_key" | "local_endpoint";
  apiBaseUrl?: string;
  source?: "snapshot" | "models_dev" | "user";
}

const PROVIDER_LABELS: Record<string, string> = {
  openai: "OpenAI",
  anthropic: "Anthropic",
  google: "Google",
  xai: "xAI",
  groq: "Groq",
  cerebras: "Cerebras",
  vercel: "Vercel AI Gateway",
  ollama: "Ollama",
  lmstudio: "LM Studio",
  mlx: "MLX",
  custom: "Custom Endpoint",
};

export function getProviderCatalogMeta(): ProviderCatalogMeta[] {
  return Array.from(new Set(CLIENT_MODEL_CATALOG.map((model) => model.provider_id))).map((id) => ({
    id,
    label: PROVIDER_LABELS[id] ?? id,
    credentialKind:
      id === "ollama" || id === "lmstudio" || id === "mlx" || id === "custom"
        ? "local_endpoint"
        : "api_key",
    source: "snapshot",
  }));
}
